### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by D4ftR0ck** [king-millez/snapmap-archiver#11]
I have the impression that when you export the json with the command --write-json the file generates this kind of output:
"create_time": "1673031690121"

If we do :
date -d @1673031690121
Thu April 06, 54986 19:02:01 CEST

but if we remove the last three characters :
date -d @1673031690
Fri Jan 06 2023 20:01:30 CET

which seems to correspond more to the real date.

I assume the date is taken by snapmap explorer, but there seems to be a format problem.

**Comment by D4ftR0ck** [comment]
By the way I have a one hour difference between the server time with the api and the code and the time obtained with the url. 

But I have no explanation haha!

**Comment by king-millez** [comment]
I'll change the date return to a floating point number.

What do you mean by the one hour difference - would you be able to paste examples?

> By the way I have a one hour difference between the server time with the api and the code and the time obtained with the url.
> 
> But I have no explanation haha!

**Comment by D4ftR0ck** [comment]
My browser was putting the metadata with the CET/GMT format. I use Paris time. But the server is with UTC (script), the English time. 
date -u -d '@1672779830'
With this command it's perfect!

**Comment by king-millez** [comment]
Does the server time still work correctly? E.g, new snaps are being displayed when they should be? If this is not an issue I won't change timezone support.

**Comment by D4ftR0ck** [comment]
there is no problem with time zones, you just have to pay attention to the difference between your browser and the snapchat server date.
