### ISSUE TITLE
Location with --write-json clarification

### ISSUE THREAD

**Issue by nrgetik** [king-millez/snapmap-archiver#12]
Nvm

**Comment by king-millez** [comment]
@nrgetik it's been a hot minute since I looked at this code so I might refactor the tool and think about your original issue.

**Comment by king-millez** [comment]
Check out #13 to track these changes. Will probably be merged later today or tomorrow :)

**Comment by nrgetik** [comment]
@king-millez Looks great, thanks for taking the time

I can open a separate issue for this if you want me to, but if you're feeling up to it, an option to only archive Snaps fresher than x hours/days would also be useful

**Comment by king-millez** [comment]
That's a great idea @nrgetik. Yeah open another issue and I'll get around to it hopefully this weekend.
