### ISSUE TITLE
Add option to support timing

### ISSUE THREAD

**Issue by nrgetik** [king-millez/snapmap-archiver#14]
The ability to constrain archived Snaps not only by location but also by time would be useful. Just to illustrate the idea:

```
snapmap-archiver -o . -l='LAT,LONG' -r 5000 -t 5d  --write-json

snapmap-archiver -o . -l='LAT,LONG' -r 5000 -t 36h --write-json
```

The new option being `-t` which accepts some concept of time in either hours or days (minutes seems unneccesasry, but 🤷‍♂️)

**Comment by king-millez** [comment]
I'm going to implement minutes for high-frequency events (the use cases for this tool in the past I've seen from some people are my justification).

Your suggestion of using a format like `5d` or `36h` is really good. I'm going to combine that with the option to just paste a 10 digit **UTC** timestamp.
